[package]
name = "static_site_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.12"
tera = "1.20"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
walkdir = "2.5"
toml = "0.8"
